### ISSUE TITLE
When I resize window, it becomes black screen

### ISSUE THREAD

**Issue by ifengming** [RecursiveG/Yet-Another-Input-Fix#2]
When I resize window, it becomes black screen

**Comment by RecursiveG** [comment]
What kind of operation system / version of MC / version of the mod / version of Java are you using?
I've only tested it on my laptop.
Since the mod used dozens of tricks, it may not work cross-platform and I need more info about how it works under different environments.

**Comment by ifengming** [comment]
Minecraft Launcher 1.6.11 (through bootstrap 5) started on osx...
System.getProperty('os.name') == 'Mac OS X'
System.getProperty('os.version') == '10.10.3'
System.getProperty('os.arch') == 'x86_64'
System.getProperty('java.version') == '1.6.0_65'
System.getProperty('java.vendor') == 'Apple Inc.'
System.getProperty('sun.arch.data.model') == '64'
forge	1.7.2-Forge10.12.2.1121

**Comment by RecursiveG** [comment]
I think the black screen bug was patched in commit f14b77b30d4259876e904d5e758e51a145ff95f5
But versions for Minecraft 1.7.2 were no longer maintained.
